name: End to End Playwright tests

on: [push]

jobs:
  trigger-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: trigger automated playwright tests
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{secrets.REPO_ACCESS_TOKEN}}
          repository: Lentyl/blog-ete-tests
          event-type: end-to-end-tests
          client-payload: '{"github": ${{ toJson(github)}}}'

